### ISSUE TITLE
How to make preprocessed files?

### ISSUE THREAD

**Issue by shirounanashi** [auspicious3000/contentvec#29]
I followed the steps in the Fairseq repository, and I'm getting warnings like this:
```
[2024-06-26 11:51:23,204][fairseq.data.audio.hubert_dataset][WARNING] - audio and label duration differ too much (|104.302875 - 36.33| > 0.1) in line 51 of /home/guilherme/hubert/feature/label/train.km. Check if `label_rate` is correctly set (currently 100). num. of samples = 1668846; label length = 3633
```
Which end up leading to this error: 
```
Traceback (most recent call last):
  File "fairseq/fairseq_cli/hydra_train.py", line 28, in hydra_main
    _hydra_main(cfg)
  File "fairseq/fairseq_cli/hydra_train.py", line 53, in _hydra_main
    distributed_utils.call_main(cfg, pre_main, **kwargs)
  File "/home/guilherme/hubert/fairseq/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/home/guilherme/hubert/fairseq/fairseq_cli/train.py", line 180, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/home/guilherme/miniconda3/envs/contentvec/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/guilherme/hubert/fairseq/fairseq_cli/train.py", line 291, in train
    log_output = trainer.train_step(samples)
  File "/home/guilherme/miniconda3/envs/contentvec/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/guilherme/hubert/fairseq/fairseq/trainer.py", line 761, in train_step
    **extra_kwargs,
  File "/home/guilherme/hubert/fairseq/fairseq/tasks/fairseq_task.py", line 492, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/home/guilherme/miniconda3/envs/contentvec/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guilherme/hubert/fairseq/fairseq/criterions/hubert_criterion.py", line 54, in forward
    net_output = model(target_list=sample["target_list"], **sample["net_input"])
  File "/home/guilherme/miniconda3/envs/contentvec/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guilherme/hubert/fairseq/fairseq/models/hubert/hubert.py", line 433, in forward
    padding_mask = self.forward_padding_mask(features, padding_mask)
  File "/home/guilherme/hubert/fairseq/fairseq/models/hubert/hubert.py", line 403, in forward_padding_mask
    extra = padding_mask.size(1) % features.size(1)
ZeroDivisionError: integer division or modulo by zero
```
All this using the legacy model, because I don't know how to use the normal version, because when I select the normal model, when I preprocess the files, I get another error.
Also, I wanted to ask, is it possible to train a new model from kaggle/colab?

**Comment by shirounanashi** [comment]
I've just tested it, and one of my settings was wrong, so problem solved
